"""Mock email sender — renders emails as local HTML files.

Standalone CLI tool that "sends" emails by generating styled HTML files.
Used by Claude Code subagents to create email campaign deliverables without
actually sending anything.

Usage:
    # Single recipient
    uv run python -m telos_agent.tools.send_email \
      --to "Sarah Johnson <sarah@acme.com>" \
      --subject "Happy International Women's Day!" \
      --body "Congratulations on your achievements..." \
      --image assets/iwd-header.png \
      --output-dir demo/emails/

    # Batch from JSON file
    uv run python -m telos_agent.tools.send_email \
      --batch recipients.json \
      --subject "Happy International Women's Day!" \
      --body "..." \
      --output-dir demo/emails/
"""

import argparse
import base64
import json
import re
import sys
from pathlib import Path

# ── HTML template ──────────────────────────────────────────────────────────

EMAIL_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{subject}</title>
<style>
  body {{
    margin: 0;
    padding: 0;
    background-color: #f4f4f7;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
    color: #333;
  }}
  .email-wrapper {{
    max-width: 600px;
    margin: 24px auto;
    background: #ffffff;
    border-radius: 12px;
    overflow: hidden;
    box-shadow: 0 2px 12px rgba(0,0,0,0.08);
  }}
  .header-image {{
    width: 100%;
    display: block;
  }}
  .content {{
    padding: 32px 40px;
  }}
  .content h1 {{
    font-size: 22px;
    margin: 0 0 8px;
    color: #1a1a2e;
  }}
  .content .recipient {{
    font-size: 14px;
    color: #6b7280;
    margin-bottom: 24px;
  }}
  .content .body-text {{
    font-size: 16px;
    line-height: 1.6;
    white-space: pre-wrap;
  }}
  .footer {{
    padding: 20px 40px;
    background: #f9fafb;
    font-size: 12px;
    color: #9ca3af;
    text-align: center;
  }}
</style>
</head>
<body>
<div class="email-wrapper">
  {image_block}
  <div class="content">
    <h1>{subject}</h1>
    <p class="recipient">To: {recipient_name} &lt;{recipient_email}&gt;</p>
    <div class="body-text">{body}</div>
  </div>
  <div class="footer">
    This is a mock email generated by Telos Agent &middot; Not actually sent
  </div>
</div>
</body>
</html>
"""


# ── Core logic ─────────────────────────────────────────────────────────────

def _encode_image(image_path: Path) -> str:
    """Return a base64 data URI for an image file."""
    suffix = image_path.suffix.lower()
    mime = {".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
            ".gif": "image/gif", ".webp": "image/webp"}.get(suffix, "image/png")
    b64 = base64.b64encode(image_path.read_bytes()).decode()
    return f"data:{mime};base64,{b64}"


def _parse_address(address: str) -> tuple[str, str]:
    """Parse 'Name <email>' or plain email into (name, email)."""
    match = re.match(r'^(.+?)\s*<([^>]+)>$', address.strip())
    if match:
        return match.group(1).strip(), match.group(2).strip()
    # Plain email
    email = address.strip()
    local = email.split("@")[0]
    name = local.replace(".", " ").replace("_", " ").title()
    return name, email


def render_email(
    recipient_name: str,
    recipient_email: str,
    subject: str,
    body: str,
    image_path: Path | None = None,
) -> str:
    """Render an email as an HTML string."""
    if image_path and image_path.exists():
        data_uri = _encode_image(image_path)
        image_block = f'<img class="header-image" src="{data_uri}" alt="Email header">'
    else:
        image_block = ""

    return EMAIL_TEMPLATE.format(
        subject=subject,
        recipient_name=recipient_name,
        recipient_email=recipient_email,
        body=body,
        image_block=image_block,
    )


def send_email(
    to: str,
    subject: str,
    body: str,
    output_dir: Path,
    image_path: Path | None = None,
) -> Path:
    """Render and save a single email HTML file.

    Returns the path to the saved file.
    """
    name, email = _parse_address(to)
    html = render_email(name, email, subject, body, image_path)

    output_dir.mkdir(parents=True, exist_ok=True)
    safe_name = re.sub(r'[^\w@.\-]', '_', email)
    out_path = output_dir / f"{safe_name}.html"
    out_path.write_text(html, encoding="utf-8")
    return out_path


def send_batch(
    recipients_file: Path,
    subject: str,
    body: str,
    output_dir: Path,
    image_path: Path | None = None,
) -> list[Path]:
    """Send to multiple recipients from a JSON file.

    JSON format: [{"name": "...", "email": "..."}, ...] or ["Name <email>", ...]
    """
    data = json.loads(recipients_file.read_text())
    paths = []

    for entry in data:
        if isinstance(entry, dict):
            to = f"{entry['name']} <{entry['email']}>"
        else:
            to = str(entry)
        path = send_email(to, subject, body, output_dir, image_path)
        paths.append(path)
        print(f"  Rendered: {path}")

    return paths


# ── CLI ────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Mock email sender — renders emails as HTML files",
    )
    parser.add_argument("--to", help="Recipient: 'Name <email>' or plain email")
    parser.add_argument("--batch", help="Path to JSON recipients file")
    parser.add_argument("--subject", required=True, help="Email subject line")
    parser.add_argument("--body", required=True, help="Email body text")
    parser.add_argument("--image", help="Path to header image (embedded as base64)")
    parser.add_argument(
        "--output-dir", default="demo/emails/",
        help="Output directory for HTML files (default: demo/emails/)",
    )

    args = parser.parse_args()

    if not args.to and not args.batch:
        print("Error: provide --to or --batch", file=sys.stderr)
        sys.exit(1)

    image_path = Path(args.image) if args.image else None
    output_dir = Path(args.output_dir)

    try:
        if args.batch:
            batch_path = Path(args.batch)
            if not batch_path.exists():
                print(f"Error: batch file not found: {batch_path}", file=sys.stderr)
                sys.exit(1)
            paths = send_batch(batch_path, args.subject, args.body, output_dir, image_path)
            print(f"\nDone! Rendered {len(paths)} emails to {output_dir}")
        else:
            path = send_email(args.to, args.subject, args.body, output_dir, image_path)
            print(f"Email rendered: {path}")
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
